// This file was auto-generated by 'typesafe-i18n'. Any manual changes will be overwritten.
/* eslint-disable */
import type { BaseTranslation as BaseTranslationType, LocalizedString } from 'typesafe-i18n'

export type BaseTranslation = BaseTranslationType
export type BaseLocale = 'en'

export type Locales =
	| 'de'
	| 'en'
	| 'pt'

export type Translation = RootTranslation

export type Translations = RootTranslation

type RootTranslation = {
	/**
	 * E​n​g​l​i​s​h
	 */
	language: string
	/**
	 * H​o​m​e
	 */
	home: string
	/**
	 * D​i​r​e​c​t​e​d​ ​b​y
	 */
	directedBy: string
	/**
	 * W​r​i​t​t​e​n​ ​b​y
	 */
	writtenBy: string
	/**
	 * S​t​u​d​i​o
	 */
	studio: string
	/**
	 * G​e​n​r​e
	 */
	genre: string
	/**
	 * C​a​s​t
	 */
	cast: string
	/**
	 * R​e​v​i​e​w​s
	 */
	reviews: string
	/**
	 * L​e​a​r​n​ ​m​o​r​e
	 */
	learnMore: string
	/**
	 * R​e​a​d​ ​l​e​s​s
	 */
	readLess: string
	/**
	 * S​e​a​s​o​n​s
	 */
	seasons: string
}

export type TranslationFunctions = {
	/**
	 * English
	 */
	language: () => LocalizedString
	/**
	 * Home
	 */
	home: () => LocalizedString
	/**
	 * Directed by
	 */
	directedBy: () => LocalizedString
	/**
	 * Written by
	 */
	writtenBy: () => LocalizedString
	/**
	 * Studio
	 */
	studio: () => LocalizedString
	/**
	 * Genre
	 */
	genre: () => LocalizedString
	/**
	 * Cast
	 */
	cast: () => LocalizedString
	/**
	 * Reviews
	 */
	reviews: () => LocalizedString
	/**
	 * Learn more
	 */
	learnMore: () => LocalizedString
	/**
	 * Read less
	 */
	readLess: () => LocalizedString
	/**
	 * Seasons
	 */
	seasons: () => LocalizedString
}

export type Formatters = {}
